///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AddTestScanModelData {
/*
{
  "user_id": 3,
  "member_id": "2",
  "name": "test",
  "provider": "nbv nbvgv",
  "scan_test": "29/05/2024",
  "updated_at": "2024-05-28T10:05:33.000000Z",
  "created_at": "2024-05-28T10:05:33.000000Z",
  "id": 7
} 
*/

  int? userId;
  String? memberId;
  String? name;
  String? provider;
  String? scanTest;
  String? updatedAt;
  String? createdAt;
  int? id;

  AddTestScanModelData({
    this.userId,
    this.memberId,
    this.name,
    this.provider,
    this.scanTest,
    this.updatedAt,
    this.createdAt,
    this.id,
  });
  AddTestScanModelData.fromJson(Map<String, dynamic> json) {
    userId = json['user_id']?.toInt();
    memberId = json['member_id']?.toString();
    name = json['name']?.toString();
    provider = json['provider']?.toString();
    scanTest = json['scan_test']?.toString();
    updatedAt = json['updated_at']?.toString();
    createdAt = json['created_at']?.toString();
    id = json['id']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['user_id'] = userId;
    data['member_id'] = memberId;
    data['name'] = name;
    data['provider'] = provider;
    data['scan_test'] = scanTest;
    data['updated_at'] = updatedAt;
    data['created_at'] = createdAt;
    data['id'] = id;
    return data;
  }
}

class AddTestScanModel {
/*
{
  "message": "Test Scan add Successfully",
  "status": 200,
  "data": {
    "user_id": 3,
    "member_id": "2",
    "name": "test",
    "provider": "nbv nbvgv",
    "scan_test": "29/05/2024",
    "updated_at": "2024-05-28T10:05:33.000000Z",
    "created_at": "2024-05-28T10:05:33.000000Z",
    "id": 7
  }
} 
*/

  String? message;
  int? status;
  AddTestScanModelData? data;

  AddTestScanModel({
    this.message,
    this.status,
    this.data,
  });
  AddTestScanModel.fromJson(Map<String, dynamic> json) {
    message = json['message']?.toString();
    status = json['status']?.toInt();
    data = (json['data'] != null) ? AddTestScanModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['message'] = message;
    data['status'] = status;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
