///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AddSympthomModelData {
/*
{
  "file": "uploads/symptoms/file/11458.jpg",
  "user_id": 2,
  "member_id": "1",
  "comment": "when they eat strawberry, then its happen strawberry allergy A tingling or burning sensation in the mouth and lips.",
  "date": "Sat, 25 May 2024",
  "time": "12:05 PM",
  "updated_at": "2024-05-25T08:10:41.000000Z",
  "created_at": "2024-05-25T08:10:41.000000Z",
  "id": 2
} 
*/

  String? file;
  int? userId;
  String? memberId;
  String? comment;
  String? date;
  String? time;
  String? updatedAt;
  String? createdAt;
  int? id;

  AddSympthomModelData({
    this.file,
    this.userId,
    this.memberId,
    this.comment,
    this.date,
    this.time,
    this.updatedAt,
    this.createdAt,
    this.id,
  });
  AddSympthomModelData.fromJson(Map<String, dynamic> json) {
    file = json['file']?.toString();
    userId = json['user_id']?.toInt();
    memberId = json['member_id']?.toString();
    comment = json['comment']?.toString();
    date = json['date']?.toString();
    time = json['time']?.toString();
    updatedAt = json['updated_at']?.toString();
    createdAt = json['created_at']?.toString();
    id = json['id']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['file'] = file;
    data['user_id'] = userId;
    data['member_id'] = memberId;
    data['comment'] = comment;
    data['date'] = date;
    data['time'] = time;
    data['updated_at'] = updatedAt;
    data['created_at'] = createdAt;
    data['id'] = id;
    return data;
  }
}

class AddSympthomModel {
/*
{
  "message": "Symptoms add Successfully",
  "status": 200,
  "data": {
    "file": "uploads/symptoms/file/11458.jpg",
    "user_id": 2,
    "member_id": "1",
    "comment": "when they eat strawberry, then its happen strawberry allergy A tingling or burning sensation in the mouth and lips.",
    "date": "Sat, 25 May 2024",
    "time": "12:05 PM",
    "updated_at": "2024-05-25T08:10:41.000000Z",
    "created_at": "2024-05-25T08:10:41.000000Z",
    "id": 2
  }
} 
*/

  String? message;
  int? status;
  AddSympthomModelData? data;

  AddSympthomModel({
    this.message,
    this.status,
    this.data,
  });
  AddSympthomModel.fromJson(Map<String, dynamic> json) {
    message = json['message']?.toString();
    status = json['status']?.toInt();
    data = (json['data'] != null) ? AddSympthomModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['message'] = message;
    data['status'] = status;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
