// ///
// /// Code generated by jsonToDartModel http://json.fluttergeeks.in/
// ///
// class SeachModelDataSymptoms {
// /*
// {
//   "id": 1,
//   "user_id": "3",
//   "member_id": "6",
//   "comment": "Strawberry allergy is an allergic reaction that occurs when the immune system identifies the proteins in strawberries as harmful substances and produces an allergic response. The primary allergen in strawberries is called Fra a1, but other proteins may al",
//   "date": "Tue, 28 May 2024",
//   "time": "4:05 PM",
//   "file": "uploads/symptoms/file/68464.jpg",
//   "status": 1,
//   "created_at": "2024-05-28T10:43:51.000000Z",
//   "updated_at": "2024-05-28T10:43:51.000000Z",
//   "member": null
// } 
// */

//   int? id;
//   String? userId;
//   String? memberId;
//   String? comment;
//   String? date;
//   String? time;
//   String? file;
//   int? status;
//   String? createdAt;
//   String? updatedAt;
//   String? member;

//   SeachModelDataSymptoms({
//     this.id,
//     this.userId,
//     this.memberId,
//     this.comment,
//     this.date,
//     this.time,
//     this.file,
//     this.status,
//     this.createdAt,
//     this.updatedAt,
//     this.member,
//   });
//   SeachModelDataSymptoms.fromJson(Map<String, dynamic> json) {
//     id = json['id']?.toInt();
//     userId = json['user_id']?.toString();
//     memberId = json['member_id']?.toString();
//     comment = json['comment']?.toString();
//     date = json['date']?.toString();
//     time = json['time']?.toString();
//     file = json['file']?.toString();
//     status = json['status']?.toInt();
//     createdAt = json['created_at']?.toString();
//     updatedAt = json['updated_at']?.toString();
//     member = json['member']?.toString();
//   }
//   Map<String, dynamic> toJson() {
//     final data = <String, dynamic>{};
//     data['id'] = id;
//     data['user_id'] = userId;
//     data['member_id'] = memberId;
//     data['comment'] = comment;
//     data['date'] = date;
//     data['time'] = time;
//     data['file'] = file;
//     data['status'] = status;
//     data['created_at'] = createdAt;
//     data['updated_at'] = updatedAt;
//     data['member'] = member;
//     return data;
//   }
// }

// class SeachModelDataMedicationMember {
// /*
// {
//   "id": 1,
//   "user_id": "3",
//   "name": "Max",
//   "dob": "27/05/2019",
//   "relation": "Son",
//   "profile": "uploads/member/profile/72666.jpg",
//   "health_insurance_information": "Not Now",
//   "health_insurance_document": null,
//   "id_proof": null,
//   "status": 1,
//   "created_at": "2024-05-28T11:11:59.000000Z",
//   "updated_at": "2024-05-28T11:11:59.000000Z"
// } 
// */

//   int? id;
//   String? userId;
//   String? name;
//   String? dob;
//   String? relation;
//   String? profile;
//   String? healthInsuranceInformation;
//   String? healthInsuranceDocument;
//   String? idProof;
//   int? status;
//   String? createdAt;
//   String? updatedAt;

//   SeachModelDataMedicationMember({
//     this.id,
//     this.userId,
//     this.name,
//     this.dob,
//     this.relation,
//     this.profile,
//     this.healthInsuranceInformation,
//     this.healthInsuranceDocument,
//     this.idProof,
//     this.status,
//     this.createdAt,
//     this.updatedAt,
//   });
//   SeachModelDataMedicationMember.fromJson(Map<String, dynamic> json) {
//     id = json['id']?.toInt();
//     userId = json['user_id']?.toString();
//     name = json['name']?.toString();
//     dob = json['dob']?.toString();
//     relation = json['relation']?.toString();
//     profile = json['profile']?.toString();
//     healthInsuranceInformation = json['health_insurance_information']?.toString();
//     healthInsuranceDocument = json['health_insurance_document']?.toString();
//     idProof = json['id_proof']?.toString();
//     status = json['status']?.toInt();
//     createdAt = json['created_at']?.toString();
//     updatedAt = json['updated_at']?.toString();
//   }
//   Map<String, dynamic> toJson() {
//     final data = <String, dynamic>{};
//     data['id'] = id;
//     data['user_id'] = userId;
//     data['name'] = name;
//     data['dob'] = dob;
//     data['relation'] = relation;
//     data['profile'] = profile;
//     data['health_insurance_information'] = healthInsuranceInformation;
//     data['health_insurance_document'] = healthInsuranceDocument;
//     data['id_proof'] = idProof;
//     data['status'] = status;
//     data['created_at'] = createdAt;
//     data['updated_at'] = updatedAt;
//     return data;
//   }
// }

// class SeachModelDataMedication {
// /*
// {
//   "id": 2,
//   "user_id": "3",
//   "member_id": "1",
//   "name": "Test",
//   "dosage": "500mg",
//   "dosage_form": "Custom type",
//   "prescription": "True",
//   "over_the_counter": "True",
//   "administration_option": "PM",
//   "start_date": "30/05/2024",
//   "end_date": "29/05/2024",
//   "custom": null,
//   "date_and_time": "28/05/2024 19 : 35  pm",
//   "nitify_for_medication": "1",
//   "comment": "Test test Test test Test test Test test Test test  Test test Test test Test test Test test Test test Test test Test test Test test Test test Test test",
//   "file": "uploads/medication/file/24288.jpg",
//   "status": 1,
//   "created_at": "2024-05-30T12:59:08.000000Z",
//   "updated_at": "2024-05-30T12:59:08.000000Z",
//   "member": {
//     "id": 1,
//     "user_id": "3",
//     "name": "Max",
//     "dob": "27/05/2019",
//     "relation": "Son",
//     "profile": "uploads/member/profile/72666.jpg",
//     "health_insurance_information": "Not Now",
//     "health_insurance_document": null,
//     "id_proof": null,
//     "status": 1,
//     "created_at": "2024-05-28T11:11:59.000000Z",
//     "updated_at": "2024-05-28T11:11:59.000000Z"
//   }
// } 
// */

//   int? id;
//   String? userId;
//   String? memberId;
//   String? name;
//   String? dosage;
//   String? dosageForm;
//   String? prescription;
//   String? overTheCounter;
//   String? administrationOption;
//   String? startDate;
//   String? endDate;
//   String? custom;
//   String? dateAndTime;
//   String? nitifyForMedication;
//   String? comment;
//   String? file;
//   int? status;
//   String? createdAt;
//   String? updatedAt;
//   SeachModelDataMedicationMember? member;

//   SeachModelDataMedication({
//     this.id,
//     this.userId,
//     this.memberId,
//     this.name,
//     this.dosage,
//     this.dosageForm,
//     this.prescription,
//     this.overTheCounter,
//     this.administrationOption,
//     this.startDate,
//     this.endDate,
//     this.custom,
//     this.dateAndTime,
//     this.nitifyForMedication,
//     this.comment,
//     this.file,
//     this.status,
//     this.createdAt,
//     this.updatedAt,
//     this.member,
//   });
//   SeachModelDataMedication.fromJson(Map<String, dynamic> json) {
//     id = json['id']?.toInt();
//     userId = json['user_id']?.toString();
//     memberId = json['member_id']?.toString();
//     name = json['name']?.toString();
//     dosage = json['dosage']?.toString();
//     dosageForm = json['dosage_form']?.toString();
//     prescription = json['prescription']?.toString();
//     overTheCounter = json['over_the_counter']?.toString();
//     administrationOption = json['administration_option']?.toString();
//     startDate = json['start_date']?.toString();
//     endDate = json['end_date']?.toString();
//     custom = json['custom']?.toString();
//     dateAndTime = json['date_and_time']?.toString();
//     nitifyForMedication = json['nitify_for_medication']?.toString();
//     comment = json['comment']?.toString();
//     file = json['file']?.toString();
//     status = json['status']?.toInt();
//     createdAt = json['created_at']?.toString();
//     updatedAt = json['updated_at']?.toString();
//     member = (json['member'] != null) ? SeachModelDataMedicationMember.fromJson(json['member']) : null;
//   }
//   Map<String, dynamic> toJson() {
//     final data = <String, dynamic>{};
//     data['id'] = id;
//     data['user_id'] = userId;
//     data['member_id'] = memberId;
//     data['name'] = name;
//     data['dosage'] = dosage;
//     data['dosage_form'] = dosageForm;
//     data['prescription'] = prescription;
//     data['over_the_counter'] = overTheCounter;
//     data['administration_option'] = administrationOption;
//     data['start_date'] = startDate;
//     data['end_date'] = endDate;
//     data['custom'] = custom;
//     data['date_and_time'] = dateAndTime;
//     data['nitify_for_medication'] = nitifyForMedication;
//     data['comment'] = comment;
//     data['file'] = file;
//     data['status'] = status;
//     data['created_at'] = createdAt;
//     data['updated_at'] = updatedAt;
//     if (member != null) {
//       data['member'] = member!.toJson();
//     }
//     return data;
//   }
// }

// class SeachModelDataTestScan {
// /*
// {
//   "id": 1,
//   "user_id": "3",
//   "member_id": "6",
//   "name": "Blood Test",
//   "provider": "Dr singh",
//   "scan_test": "29/05/2024",
//   "add_comment": null,
//   "file": "uploads/procedures/file/33508.jpg",
//   "status": 1,
//   "created_at": "2024-05-28T10:40:58.000000Z",
//   "updated_at": "2024-05-28T10:40:58.000000Z",
//   "member": null
// } 
// */

//   int? id;
//   String? userId;
//   String? memberId;
//   String? name;
//   String? provider;
//   String? scanTest;
//   String? addComment;
//   String? file;
//   int? status;
//   String? createdAt;
//   String? updatedAt;
//   String? member;

//   SeachModelDataTestScan({
//     this.id,
//     this.userId,
//     this.memberId,
//     this.name,
//     this.provider,
//     this.scanTest,
//     this.addComment,
//     this.file,
//     this.status,
//     this.createdAt,
//     this.updatedAt,
//     this.member,
//   });
//   SeachModelDataTestScan.fromJson(Map<String, dynamic> json) {
//     id = json['id']?.toInt();
//     userId = json['user_id']?.toString();
//     memberId = json['member_id']?.toString();
//     name = json['name']?.toString();
//     provider = json['provider']?.toString();
//     scanTest = json['scan_test']?.toString();
//     addComment = json['add_comment']?.toString();
//     file = json['file']?.toString();
//     status = json['status']?.toInt();
//     createdAt = json['created_at']?.toString();
//     updatedAt = json['updated_at']?.toString();
//     member = json['member']?.toString();
//   }
//   Map<String, dynamic> toJson() {
//     final data = <String, dynamic>{};
//     data['id'] = id;
//     data['user_id'] = userId;
//     data['member_id'] = memberId;
//     data['name'] = name;
//     data['provider'] = provider;
//     data['scan_test'] = scanTest;
//     data['add_comment'] = addComment;
//     data['file'] = file;
//     data['status'] = status;
//     data['created_at'] = createdAt;
//     data['updated_at'] = updatedAt;
//     data['member'] = member;
//     return data;
//   }
// }

// class SeachModelDataProcedures {
// /*
// {
//   "id": 1,
//   "user_id": "3",
//   "member_id": "6",
//   "type": "Test",
//   "provider": "Dr singh",
//   "date_of_procedure": "29/05/2024",
//   "add_comment": null,
//   "file": "uploads/procedures/file/27126.jpg",
//   "status": 1,
//   "created_at": "2024-05-28T10:46:06.000000Z",
//   "updated_at": "2024-05-28T10:46:06.000000Z",
//   "member": null
// } 
// */

//   int? id;
//   String? userId;
//   String? memberId;
//   String? type;
//   String? provider;
//   String? dateOfProcedure;
//   String? addComment;
//   String? file;
//   int? status;
//   String? createdAt;
//   String? updatedAt;
//   String? member;

//   SeachModelDataProcedures({
//     this.id,
//     this.userId,
//     this.memberId,
//     this.type,
//     this.provider,
//     this.dateOfProcedure,
//     this.addComment,
//     this.file,
//     this.status,
//     this.createdAt,
//     this.updatedAt,
//     this.member,
//   });
//   SeachModelDataProcedures.fromJson(Map<String, dynamic> json) {
//     id = json['id']?.toInt();
//     userId = json['user_id']?.toString();
//     memberId = json['member_id']?.toString();
//     type = json['type']?.toString();
//     provider = json['provider']?.toString();
//     dateOfProcedure = json['date_of_procedure']?.toString();
//     addComment = json['add_comment']?.toString();
//     file = json['file']?.toString();
//     status = json['status']?.toInt();
//     createdAt = json['created_at']?.toString();
//     updatedAt = json['updated_at']?.toString();
//     member = json['member']?.toString();
//   }
//   Map<String, dynamic> toJson() {
//     final data = <String, dynamic>{};
//     data['id'] = id;
//     data['user_id'] = userId;
//     data['member_id'] = memberId;
//     data['type'] = type;
//     data['provider'] = provider;
//     data['date_of_procedure'] = dateOfProcedure;
//     data['add_comment'] = addComment;
//     data['file'] = file;
//     data['status'] = status;
//     data['created_at'] = createdAt;
//     data['updated_at'] = updatedAt;
//     data['member'] = member;
//     return data;
//   }
// }

// class SeachModelDataAppointment {
// /*
// {
//   "id": 1,
//   "user_id": "3",
//   "member_id": "6",
//   "provider_id": "1",
//   "visit_date": "29/05/2024",
//   "question_for_provider": "Body Test",
//   "provider_comment": "Full Body checkup",
//   "note": "Airm and Head",
//   "photo": "uploads/appointment/photo/96950.jpg",
//   "status": 1,
//   "created_at": "2024-05-28T10:50:59.000000Z",
//   "updated_at": "2024-05-28T10:50:59.000000Z",
//   "member": null
// } 
// */

//   int? id;
//   String? userId;
//   String? memberId;
//   String? providerId;
//   String? visitDate;
//   String? questionForProvider;
//   String? providerComment;
//   String? note;
//   String? photo;
//   int? status;
//   String? createdAt;
//   String? updatedAt;
//   String? member;

//   SeachModelDataAppointment({
//     this.id,
//     this.userId,
//     this.memberId,
//     this.providerId,
//     this.visitDate,
//     this.questionForProvider,
//     this.providerComment,
//     this.note,
//     this.photo,
//     this.status,
//     this.createdAt,
//     this.updatedAt,
//     this.member,
//   });
//   SeachModelDataAppointment.fromJson(Map<String, dynamic> json) {
//     id = json['id']?.toInt();
//     userId = json['user_id']?.toString();
//     memberId = json['member_id']?.toString();
//     providerId = json['provider_id']?.toString();
//     visitDate = json['visit_date']?.toString();
//     questionForProvider = json['question_for_provider']?.toString();
//     providerComment = json['provider_comment']?.toString();
//     note = json['note']?.toString();
//     photo = json['photo']?.toString();
//     status = json['status']?.toInt();
//     createdAt = json['created_at']?.toString();
//     updatedAt = json['updated_at']?.toString();
//     member = json['member']?.toString();
//   }
//   Map<String, dynamic> toJson() {
//     final data = <String, dynamic>{};
//     data['id'] = id;
//     data['user_id'] = userId;
//     data['member_id'] = memberId;
//     data['provider_id'] = providerId;
//     data['visit_date'] = visitDate;
//     data['question_for_provider'] = questionForProvider;
//     data['provider_comment'] = providerComment;
//     data['note'] = note;
//     data['photo'] = photo;
//     data['status'] = status;
//     data['created_at'] = createdAt;
//     data['updated_at'] = updatedAt;
//     data['member'] = member;
//     return data;
//   }
// }

import 'package:my_health_journal/models/home/appointment_list_model.dart';
import 'package:my_health_journal/models/home/get_test_scan_model.dart';
import 'package:my_health_journal/models/home/medication_list_model.dart';
import 'package:my_health_journal/models/home/procedures_list_model.dart';
import 'package:my_health_journal/models/home/provider_view_model.dart';
import 'package:my_health_journal/models/home/symphtom_list_model.dart';
import 'package:my_health_journal/models/patient_list_model.dart';

class SeachModelData {


  List<PatientListMember>? member;
  List<AppointmentListModelData>? appointment;
  List<ProceduresListModelData>? procedures;
  List<GetTestScanModelData>? testScan;
  List<MedicationListModelData>? medication;
  List<SymphtomListModelData>? symptoms;
  List<ProviderViewModelData>? provider;

  SeachModelData({
    this.member,
    this.appointment,
    this.procedures,
    this.testScan,
    this.medication,
    this.symptoms,
    this.provider,
  });
  SeachModelData.fromJson(Map<String, dynamic> json) {
  if (json['member'] != null) {
  final v = json['member'];
  final arr0 = <PatientListMember>[];
  v.forEach((v) {
  arr0.add(PatientListMember.fromJson(v));
  });
    member = arr0;
  }
  if (json['appointment'] != null) {
  final v = json['appointment'];
  final arr0 = <AppointmentListModelData>[];
  v.forEach((v) {
  arr0.add(AppointmentListModelData.fromJson(v));
  });
    this.appointment = arr0;
  }
  if (json['procedures'] != null) {
  final v = json['procedures'];
  final arr0 = <ProceduresListModelData>[];
  v.forEach((v) {
  arr0.add(ProceduresListModelData.fromJson(v));
  });
    procedures = arr0;
    }
  if (json['test_scan'] != null) {
  final v = json['test_scan'];
  final arr0 = <GetTestScanModelData>[];
  v.forEach((v) {
  arr0.add(GetTestScanModelData.fromJson(v));
  });
    testScan = arr0;
  }
  if (json['medication'] != null) {
  final v = json['medication'];
  final arr0 = <MedicationListModelData>[];
  v.forEach((v) {
  arr0.add(MedicationListModelData.fromJson(v));
  });
    medication = arr0;
    }
  if (json['symptoms'] != null) {
  final v = json['symptoms'];
  final arr0 = <SymphtomListModelData>[];
  v.forEach((v) {
  arr0.add(SymphtomListModelData.fromJson(v));
  });
    symptoms = arr0;
    }
  if (json['provider'] != null) {
  final v = json['provider'];
  final arr0 = <ProviderViewModelData>[];
  v.forEach((v) {
  arr0.add(ProviderViewModelData.fromJson(v));
  });
    provider = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
     if (member != null) {
      final v = member;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v.toJson());
  });
      data['member'] = arr0;
    }
    if (appointment != null) {
      final v = appointment;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v.toJson());
  });
      data['appointment'] = arr0;
    }
    if (procedures != null) {
      final v = procedures;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v.toJson());
  });
      data['procedures'] = arr0;
    }
    if (testScan != null) {
      final v = testScan;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v.toJson());
  });
      data['test_scan'] = arr0;
    }
    if (medication != null) {
      final v = medication;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v.toJson());
  });
      data['medication'] = arr0;
    }
    if (symptoms != null) {
      final v = symptoms;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v.toJson());
  });
      data['provider'] = arr0;
    }
     if (provider != null) {
      final v = provider;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v.toJson());
  });
      data['provider'] = arr0;
    }
    return data;
  }
}

class SeachModel {
/*
{
  "message": "Data Fetach Successfully.",
  "status": 200,
  "success": true,
  "data": {
    "member": [
      null
    ],
    "appointment": [
      {
        "id": 1,
        "user_id": "3",
        "member_id": "6",
        "provider_id": "1",
        "visit_date": "29/05/2024",
        "question_for_provider": "Body Test",
        "provider_comment": "Full Body checkup",
        "note": "Airm and Head",
        "photo": "uploads/appointment/photo/96950.jpg",
        "status": 1,
        "created_at": "2024-05-28T10:50:59.000000Z",
        "updated_at": "2024-05-28T10:50:59.000000Z",
        "member": null
      }
    ],
    "procedures": [
      {
        "id": 1,
        "user_id": "3",
        "member_id": "6",
        "type": "Test",
        "provider": "Dr singh",
        "date_of_procedure": "29/05/2024",
        "add_comment": null,
        "file": "uploads/procedures/file/27126.jpg",
        "status": 1,
        "created_at": "2024-05-28T10:46:06.000000Z",
        "updated_at": "2024-05-28T10:46:06.000000Z",
        "member": null
      }
    ],
    "test_scan": [
      {
        "id": 1,
        "user_id": "3",
        "member_id": "6",
        "name": "Blood Test",
        "provider": "Dr singh",
        "scan_test": "29/05/2024",
        "add_comment": null,
        "file": "uploads/procedures/file/33508.jpg",
        "status": 1,
        "created_at": "2024-05-28T10:40:58.000000Z",
        "updated_at": "2024-05-28T10:40:58.000000Z",
        "member": null
      }
    ],
    "medication": [
      {
        "id": 2,
        "user_id": "3",
        "member_id": "1",
        "name": "Test",
        "dosage": "500mg",
        "dosage_form": "Custom type",
        "prescription": "True",
        "over_the_counter": "True",
        "administration_option": "PM",
        "start_date": "30/05/2024",
        "end_date": "29/05/2024",
        "custom": null,
        "date_and_time": "28/05/2024 19 : 35  pm",
        "nitify_for_medication": "1",
        "comment": "Test test Test test Test test Test test Test test  Test test Test test Test test Test test Test test Test test Test test Test test Test test Test test",
        "file": "uploads/medication/file/24288.jpg",
        "status": 1,
        "created_at": "2024-05-30T12:59:08.000000Z",
        "updated_at": "2024-05-30T12:59:08.000000Z",
        "member": {
          "id": 1,
          "user_id": "3",
          "name": "Max",
          "dob": "27/05/2019",
          "relation": "Son",
          "profile": "uploads/member/profile/72666.jpg",
          "health_insurance_information": "Not Now",
          "health_insurance_document": null,
          "id_proof": null,
          "status": 1,
          "created_at": "2024-05-28T11:11:59.000000Z",
          "updated_at": "2024-05-28T11:11:59.000000Z"
        }
      }
    ],
    "symptoms": [
      {
        "id": 1,
        "user_id": "3",
        "member_id": "6",
        "comment": "Strawberry allergy is an allergic reaction that occurs when the immune system identifies the proteins in strawberries as harmful substances and produces an allergic response. The primary allergen in strawberries is called Fra a1, but other proteins may al",
        "date": "Tue, 28 May 2024",
        "time": "4:05 PM",
        "file": "uploads/symptoms/file/68464.jpg",
        "status": 1,
        "created_at": "2024-05-28T10:43:51.000000Z",
        "updated_at": "2024-05-28T10:43:51.000000Z",
        "member": null
      }
    ],
    "provider": [
      null
    ]
  }
} 
*/

  String? message;
  int? status;
  bool? success;
  SeachModelData? data;

  SeachModel({
    this.message,
    this.status,
    this.success,
    this.data,
  });
  SeachModel.fromJson(Map<String, dynamic> json) {
    message = json['message']?.toString();
    status = json['status']?.toInt();
    success = json['success'];
    data = (json['data'] != null) ? SeachModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['message'] = message;
    data['status'] = status;
    data['success'] = success;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
