///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AppointmentListModelDataGetProvider {
/*
{
  "id": 3,
  "user_id": "2",
  "name": "Ranjan",
  "specialization": "Cancer",
  "web_url": "https://xd.adobe.com",
  "ac_number": "12345678923456",
  "phone": "123456788890",
  "visit_date": "2024-05-26",
  "report_info": "uploads/provider/report_info/58427.webp",
  "status": 1,
  "created_at": "2024-05-17T00:30:21.000000Z",
  "updated_at": "2024-05-17T00:30:21.000000Z"
} 
*/

  int? id;
  String? userId;
  String? name;
  String? specialization;
  String? webUrl;
  String? acNumber;
  String? phone;
  String? visitDate;
  String? reportInfo;
  int? status;
  String? createdAt;
  String? updatedAt;

  AppointmentListModelDataGetProvider({
    this.id,
    this.userId,
    this.name,
    this.specialization,
    this.webUrl,
    this.acNumber,
    this.phone,
    this.visitDate,
    this.reportInfo,
    this.status,
    this.createdAt,
    this.updatedAt,
  });
  AppointmentListModelDataGetProvider.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    userId = json['user_id']?.toString();
    name = json['name']?.toString();
    specialization = json['specialization']?.toString();
    webUrl = json['web_url']?.toString();
    acNumber = json['ac_number']?.toString();
    phone = json['phone']?.toString();
    visitDate = json['visit_date']?.toString();
    reportInfo = json['report_info']?.toString();
    status = json['status']?.toInt();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['user_id'] = userId;
    data['name'] = name;
    data['specialization'] = specialization;
    data['web_url'] = webUrl;
    data['ac_number'] = acNumber;
    data['phone'] = phone;
    data['visit_date'] = visitDate;
    data['report_info'] = reportInfo;
    data['status'] = status;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    return data;
  }
}

class AppointmentListModelData {
/*
{
  "id": 3,
  "user_id": "2",
  "member_id": "1",
  "provider_id": "3",
  "visit_date": "30/05/2024",
  "question_for_provider": "asa",
  "provider_comment": "as",
  "note": "as x sdxsd",
  "photo": null,
  "status": 1,
  "created_at": "2024-05-25T06:45:45.000000Z",
  "updated_at": "2024-05-25T06:45:45.000000Z",
  "get_provider": {
    "id": 3,
    "user_id": "2",
    "name": "Ranjan",
    "specialization": "Cancer",
    "web_url": "https://xd.adobe.com",
    "ac_number": "12345678923456",
    "phone": "123456788890",
    "visit_date": "2024-05-26",
    "report_info": "uploads/provider/report_info/58427.webp",
    "status": 1,
    "created_at": "2024-05-17T00:30:21.000000Z",
    "updated_at": "2024-05-17T00:30:21.000000Z"
  }
} 
*/

  int? id;
  String? userId;
  String? memberId;
  String? providerId;
  String? visitDate;
  String? questionForProvider;
  String? providerComment;
  String? note;
  String? photo;
  int? status;
  String? createdAt;
  String? updatedAt;
  AppointmentListModelDataGetProvider? getProvider;

  AppointmentListModelData({
    this.id,
    this.userId,
    this.memberId,
    this.providerId,
    this.visitDate,
    this.questionForProvider,
    this.providerComment,
    this.note,
    this.photo,
    this.status,
    this.createdAt,
    this.updatedAt,
    this.getProvider,
  });
  AppointmentListModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    userId = json['user_id']?.toString();
    memberId = json['member_id']?.toString();
    providerId = json['provider_id']?.toString();
    visitDate = json['visit_date']?.toString();
    questionForProvider = json['question_for_provider']?.toString();
    providerComment = json['provider_comment']?.toString();
    note = json['note']?.toString();
    photo = json['photo']?.toString();
    status = json['status']?.toInt();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    getProvider = (json['get_provider'] != null) ? AppointmentListModelDataGetProvider.fromJson(json['get_provider']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['user_id'] = userId;
    data['member_id'] = memberId;
    data['provider_id'] = providerId;
    data['visit_date'] = visitDate;
    data['question_for_provider'] = questionForProvider;
    data['provider_comment'] = providerComment;
    data['note'] = note;
    data['photo'] = photo;
    data['status'] = status;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    if (getProvider != null) {
      data['get_provider'] = getProvider!.toJson();
    }
    return data;
  }
}

class AppointmentListModel {
/*
{
  "message": "Data Fetach Successfully.",
  "status": 200,
  "success": true,
  "data": [
    {
      "id": 3,
      "user_id": "2",
      "member_id": "1",
      "provider_id": "3",
      "visit_date": "30/05/2024",
      "question_for_provider": "asa",
      "provider_comment": "as",
      "note": "as x sdxsd",
      "photo": null,
      "status": 1,
      "created_at": "2024-05-25T06:45:45.000000Z",
      "updated_at": "2024-05-25T06:45:45.000000Z",
      "get_provider": {
        "id": 3,
        "user_id": "2",
        "name": "Ranjan",
        "specialization": "Cancer",
        "web_url": "https://xd.adobe.com",
        "ac_number": "12345678923456",
        "phone": "123456788890",
        "visit_date": "2024-05-26",
        "report_info": "uploads/provider/report_info/58427.webp",
        "status": 1,
        "created_at": "2024-05-17T00:30:21.000000Z",
        "updated_at": "2024-05-17T00:30:21.000000Z"
      }
    }
  ]
} 
*/

  String? message;
  int? status;
  bool? success;
  List<AppointmentListModelData>? data;

  AppointmentListModel({
    this.message,
    this.status,
    this.success,
    this.data,
  });
  AppointmentListModel.fromJson(Map<String, dynamic> json) {
    message = json['message']?.toString();
    status = json['status']?.toInt();
    success = json['success'];
  if (json['data'] != null) {
  final v = json['data'];
  final arr0 = <AppointmentListModelData>[];
  v.forEach((v) {
  arr0.add(AppointmentListModelData.fromJson(v));
  });
    this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['message'] = message;
    data['status'] = status;
    data['success'] = success;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['data'] = arr0;
    }
    return data;
  }
}
